// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Z6-su9EpP8ETdhbyvq3YVB4KzviWuBA',
    appId: '1:524064964142:web:64326768e56c47e9cb69bf',
    messagingSenderId: '524064964142',
    projectId: 'virtustyler',
    authDomain: 'virtustyler.firebaseapp.com',
    storageBucket: 'virtustyler.appspot.com',
    measurementId: 'G-118CVMNX85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCjA7-ia13UlNx4O4VqZxLB_0ezy8Wes8',
    appId: '1:524064964142:android:b77970fa56bf5672cb69bf',
    messagingSenderId: '524064964142',
    projectId: 'virtustyler',
    storageBucket: 'virtustyler.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSz9oQz_J-VmVZ7aYehSqzb031fdEnVw',
    appId: '1:524064964142:ios:c97b3b366dbb1189cb69bf',
    messagingSenderId: '524064964142',
    projectId: 'virtustyler',
    storageBucket: 'virtustyler.appspot.com',
    iosBundleId: 'com.example.virtustyler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLSz9oQz_J-VmVZ7aYehSqzb031fdEnVw',
    appId: '1:524064964142:ios:4870c705107f0100cb69bf',
    messagingSenderId: '524064964142',
    projectId: 'virtustyler',
    storageBucket: 'virtustyler.appspot.com',
    iosBundleId: 'com.example.virtustyler.RunnerTests',
  );
}
